version: '3'
services:
  backend:
    restart: always
    build: ./backend
    ports:
      - 8080:8080
  frontend:
    build: ./frontend/frontend/svelte-todo-app/
    ports:
      - 5000:5000
    depends_on:
      - backend