// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "info": {
      "version": "1.0.0",
      "title": "ToDo List API",
      "description": "This is a simple docs for ToDo List API"
    },
    "paths": {
      "/todo": {
        "post": {
          "tags": [
            "ToDo"
          ],
          "summary": "add new ToDo entry",
          "parameters": [
            {
              "in": "body",
              "name": "todoText",
              "schema": {
                "type": "object",
                "required": [
                  "todoText"
                ],
                "properties": {
                  "todoText": {
                    "type": "string"
                  }
                }
              }
            }
          ],
          "description": "",
          "responses": {
            "404": {
              "description": "Not Found"
            }
          }
        },
        "get": {
          "tags": [
            "ToDo"
          ],
          "summary": "Get all ToDo entries",
          "responses": {
            "200": {
              "description": "OK"
            }
          },
          "parameters": []
        }
      },
      "/todo/{ID}": {
        "get": {
          "tags": [
            "ToDo"
          ],
          "summary": "Get the ToDo entry",
          "parameters": [
            {
              "in": "path",
              "name": "ID",
              "description": "ID of the ToDo entry",
              "required": true,
              "type": "integer"
            }
          ],
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "description": "ID Not Found"
            }
          }
        },
        "delete": {
          "tags": [
            "ToDo"
          ],
          "summary": "delete ToDo entry",
          "description": "",
          "parameters": [
            {
              "in": "path",
              "name": "ID",
              "description": "ID of the ToDo entry",
              "required": true,
              "type": "integer"
            }
          ],
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "description": "ID Not Found"
            }
          }
        },
        "put": {
          "tags": [
            "ToDo"
          ],
          "summary": "update ToDo entry",
          "description": "",
          "parameters": [
            {
              "in": "path",
              "name": "ID",
              "description": "ID of the ToDo entry",
              "required": true,
              "type": "integer"
            },
            {
              "in": "body",
              "name": "todoText",
              "schema": {
                "type": "object",
                "required": [
                  "todoText"
                ],
                "properties": {
                  "todoText": {
                    "type": "string"
                  }
                }
              }
            }
          ],
          "responses": {
            "200": {
              "description": "OK"
            },
            "404": {
              "description": "ID Not Found"
            }
          }
        }
      }
    },
    "swagger": "2.0"
  }`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
